abstract type AbstractStrategy end
initialize!(::AbstractStrategy, args...) = error("Unimplemented!")
should_run(::AbstractStrategy, args...) = error("Unimplemented!")
process_preopen!(::AbstractStrategy, args...) = error("Unimplemented!")
process_open!(::AbstractStrategy, args...) = error("Unimplemented!")
process!(::AbstractStrategy, args...) = error("Unimplemented!")
process_close!(::AbstractStrategy, args...) = error("Unimplemented!")
process_postclose!(::AbstractStrategy, args...) = error("Unimplemented!")
update_statistics!(::AbstractStrategy, args...) = error("Unimplemented!")
